version: "3.6"

services:
  lc-core:
    container_name: "libre-captcha"
    image: librecaptcha/lc-core:latest
    # Comment "image" & uncomment "build" if you intend to build from source
    #build: .
    volumes: 
      - "./docker-data:/lc-core/data"
    ports: 
      - "8888:8888"
